name: Deploy to App Engine

on: push

jobs:
  build:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: 'projects/882200096888/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'github-actions@forecasting-fantasy-football.iam.gserviceaccount.com'

    - name: gcloud
      uses: google-github-actions/setup-gcloud@v0

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: app
        push: true
        tags: gcr.io/forecasting-fantasy-football/app:latest
