name: Docker build and push

on:
  push:
    branches:
    - master

jobs:
  build:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: 'projects/882200096888/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'github-actions@forecasting-fantasy-football.iam.gserviceaccount.com'

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: app
        push: true
        tags: gcr.io/forecasting-fantasy-football/app:latest

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: forecasting-fantasy-football-app
        image: gcr.io/forecasting-fantasy-football/app:latest
        region: europe-north1

    - name: Use output
      run: |
        curl "${{ steps.deploy.outputs.url }}"
