name: Test fpl_forecast

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Test
      run: |
        pip install pytest
        pip install pytest-cov
        pip install -r fpl_forecast/requirements.txt
        python -m scripts.train_all_points --horizon 1 --outfile points.pq --score_path points_scores.pq --features_path features.pq
        python -m scripts.train_all_playing --horizon 1 --outfile playing.pq --score_path playing_scores.pq
