name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: 'projects/882200096888/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'github-actions@forecasting-fantasy-football.iam.gserviceaccount.com'

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: app
        push: false
        tags: gcr.io/forecasting-fantasy-football/app:latest

    - name: Test
      run: |
        cd app
        pip install pytest
        pip install pytest-cov
        pip install -r requirements.txt
        PYTHONPATH=. pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
